import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const candidates = readdirSync(root).filter((f) => /^layout-C-student.*\.docx$/.test(f));
if (candidates.length === 0) {
  console.log("embed: no layout-C-student*.docx in the project root — keeping src/docx.ts as is");
  process.exit(0);
}
const b64 = readFileSync(root + candidates[0]).toString("base64");
writeFileSync(
  root + "src/docx.ts",
  `// Generated by scripts/embed-docx.mjs from ${candidates[0]} — do not edit.\nexport const DOCX_BASE64 =\n  "${b64}";\n`,
);
console.log(`embed: ${candidates[0]} → src/docx.ts (${b64.length} chars)`);
